import "./globals.css";
import { Inter, Instrument_Serif } from "next/font/google";
import { cx } from "@/lib/classnames";
import { Header } from "./header";
import { Footer } from "./footer";

const inter = Inter({ subsets: ["latin"] });

const instrument = Instrument_Serif({
  variable: "--serif-font",
  subsets: ["latin"],
  weight: "400",
  style: "italic",
});

export const metadata = {
  title: "Design Engineer // Alex Carpenter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={cx(
          "bg-page py-16 px-4 antialiased max-w-[112.5rem] mx-auto",
          inter.className,
          instrument.variable
        )}
      >
        <Header />
        <main id="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
