import "./globals.css";
import { Instrument_Serif } from "next/font/google";
import localFont from "next/font/local";
import { cx } from "@/lib/classnames";
import { Header } from "./header";
import { Footer } from "./footer";

const inter = localFont({
  src: "../public/fonts/inter-var-latin.woff2",
  display: "swap",
  variable: "--font-inter",
});

const instrument = Instrument_Serif({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: "400",
  style: "italic",
});

export const metadata = {
  title: "Design Engineer // Alex Carpenter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={cx(
          "bg-page py-16 px-4 antialiased max-w-[112.5rem] mx-auto font-sans",
          inter.variable,
          instrument.variable
        )}
      >
        <Header />
        <main id="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
